import Database from 'better-sqlite3';
import { join } from 'path';
const dbPath = join(process.cwd(), 'database.sqlite');
const db = new Database(dbPath);
console.log('Clearing articles...');
db.prepare('DELETE FROM articles').run();
console.log('Clearing processes...');
db.prepare('DELETE FROM processes').run();
console.log('Clearing commitments...');
db.prepare('DELETE FROM commitments').run();
console.log('Clearing macchina_5000...');
db.prepare('DELETE FROM macchina_5000').run();
console.log('Clearing taglio_laser...');
db.prepare('DELETE FROM taglio_laser').run();
console.log('Clearing fase_taglio...');
db.prepare('DELETE FROM fase_taglio').run();
console.log('Clearing fase_saldatura...');
db.prepare('DELETE FROM fase_saldatura').run();
console.log('Clearing fase_pannelatrice...');
db.prepare('DELETE FROM fase_pannelatrice').run();
console.log('Clearing fase_piega_manuale...');
db.prepare('DELETE FROM fase_piega_manuale').run();
console.log('Clearing fase_verniciatura...');
db.prepare('DELETE FROM fase_verniciatura').run();
console.log('Done clearing tables.');
